theme = "pop-dark"

[editor]
mouse = false
true-color = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal]
ins = "insert_mode"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
ins = "normal_mode"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
